package com.redsea.pojo;

import com.redsea.pojo.base.BaseArticleRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleRegion extends BaseArticleRegion<ArticleRegion> {
	public static final ArticleRegion dao = new ArticleRegion();
}
