package com.redsea.pojo;

import com.redsea.pojo.base.BaseArticleTags;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleTags extends BaseArticleTags<ArticleTags> {
	public static final ArticleTags dao = new ArticleTags();
}
