package com.redsea.pojo;

import com.redsea.pojo.base.BaseArticleTopic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleTopic extends BaseArticleTopic<ArticleTopic> {
	public static final ArticleTopic dao = new ArticleTopic();
}
