package com.redsea.pojo;

import com.redsea.pojo.base.BaseFolder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Folder extends BaseFolder<Folder> {
	public static final Folder dao = new Folder();
}
