package com.redsea.pojo;

import com.redsea.pojo.base.BaseLogin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Login extends BaseLogin<Login> {
	public static final Login dao = new Login();
}
