package com.redsea.pojo;

import com.redsea.pojo.base.BasePeople;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class People extends BasePeople<People> {
	public static final People dao = new People();
}
