package com.redsea.pojo;

import com.redsea.pojo.base.BaseRegionCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RegionCode extends BaseRegionCode<RegionCode> {
	public static final RegionCode dao = new RegionCode();
}
