package com.redsea.pojo;

import com.redsea.pojo.base.BaseRegionUrl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RegionUrl extends BaseRegionUrl<RegionUrl> {
	public static final RegionUrl dao = new RegionUrl();
}
