package com.redsea.pojo;

import com.redsea.pojo.base.BaseSpiderRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpiderRule extends BaseSpiderRule<SpiderRule> {
	public static final SpiderRule dao = new SpiderRule();
}
