package com.redsea.pojo;

import com.redsea.pojo.base.BaseSpiderJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpiderJob extends BaseSpiderJob<SpiderJob> {
	public static final SpiderJob dao = new SpiderJob();
}
