package com.redsea.pojo;

import com.redsea.pojo.base.BaseSysCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysCode extends BaseSysCode<SysCode> {
	public static final SysCode dao = new SysCode();
}
