package com.redsea.pojo;

import com.redsea.pojo.base.BaseSysDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDict extends BaseSysDict<SysDict> {
	public static final SysDict dao = new SysDict();
}
