package com.redsea.pojo;

import com.redsea.pojo.base.BaseSysUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
	public static final SysUser dao = new SysUser();
}
