package com.redsea.pojo;

import com.redsea.pojo.base.BaseTags;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tags extends BaseTags<Tags> {
	public static final Tags dao = new Tags();
}
