package com.redsea.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.redsea.ext.base.BaseModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegionUrl<M extends BaseRegionUrl<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRegionCode(java.lang.String regionCode) {
		set("region_code", regionCode);
	}

	public java.lang.String getRegionCode() {
		return get("region_code");
	}

	public void setCodeName(java.lang.String codeName) {
		set("code_name", codeName);
	}

	public java.lang.String getCodeName() {
		return get("code_name");
	}

	public void setParentCode(java.lang.String parentCode) {
		set("parent_code", parentCode);
	}

	public java.lang.String getParentCode() {
		return get("parent_code");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
	}

	public java.lang.String getOrgName() {
		return get("org_name");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setQueryDesc(java.lang.String queryDesc) {
		set("query_desc", queryDesc);
	}

	public java.lang.String getQueryDesc() {
		return get("query_desc");
	}

}
