package com.redsea.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public void setPostId(java.lang.Long postId) {
		set("post_id", postId);
	}

	public java.lang.Long getPostId() {
		return get("post_id");
	}

	public void setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
	}

	public java.lang.Long getParentId() {
		return get("parent_id");
	}

	public void setAuthorId(java.lang.String authorId) {
		set("author_id", authorId);
	}

	public java.lang.String getAuthorId() {
		return get("author_id");
	}

	public void setAuthorName(java.lang.String authorName) {
		set("author_name", authorName);
	}

	public java.lang.String getAuthorName() {
		return get("author_name");
	}

	public void setAuthorEmail(java.lang.String authorEmail) {
		set("author_email", authorEmail);
	}

	public java.lang.String getAuthorEmail() {
		return get("author_email");
	}

	public void setAuthorUrl(java.lang.String authorUrl) {
		set("author_url", authorUrl);
	}

	public java.lang.String getAuthorUrl() {
		return get("author_url");
	}

	public void setAuthorKey(java.lang.String authorKey) {
		set("author_key", authorKey);
	}

	public java.lang.String getAuthorKey() {
		return get("author_key");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setAgent(java.lang.String agent) {
		set("agent", agent);
	}

	public java.lang.String getAgent() {
		return get("agent");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}

	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setMessage(java.lang.String message) {
		set("message", message);
	}

	public java.lang.String getMessage() {
		return get("message");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setThreadKey(java.lang.Integer threadKey) {
		set("thread_key", threadKey);
	}

	public java.lang.Integer getThreadKey() {
		return get("thread_key");
	}

	public void setLogId(java.lang.Long logId) {
		set("log_id", logId);
	}

	public java.lang.Long getLogId() {
		return get("log_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

}
