package com.redsea.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.redsea.ext.base.BaseModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setFolderId(java.lang.Integer folderId) {
		set("folder_id", folderId);
	}

	public java.lang.Integer getFolderId() {
		return get("folder_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
	}

	public java.lang.String getKeyword() {
		return get("keyword");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}

	public java.lang.String getSummary() {
		return get("summary");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setOrigin(java.lang.String origin) {
		set("origin", origin);
	}

	public java.lang.String getOrigin() {
		return get("origin");
	}

	public void setOriginUrl(java.lang.String originUrl) {
		set("origin_url", originUrl);
	}

	public java.lang.String getOriginUrl() {
		return get("origin_url");
	}

	public void setLink(java.lang.String link) {
		set("link", link);
	}

	public java.lang.String getLink() {
		return get("link");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setColor(java.lang.String color) {
		set("color", color);
	}

	public java.lang.String getColor() {
		return get("color");
	}

	public void setTemplate(java.lang.String template) {
		set("template", template);
	}

	public java.lang.String getTemplate() {
		return get("template");
	}

	public void setTopicId(java.lang.String topicId) {
		set("topic_id", topicId);
	}

	public java.lang.String getTopicId() {
		return get("topic_id");
	}

	public void setIsRecommend(java.lang.Integer isRecommend) {
		set("is_recommend", isRecommend);
	}

	public java.lang.Integer getIsRecommend() {
		return get("is_recommend");
	}

	public void setIsBanner(java.lang.Integer isBanner) {
		set("is_banner", isBanner);
	}

	public java.lang.Integer getIsBanner() {
		return get("is_banner");
	}

	public void setCountComment(java.lang.Integer countComment) {
		set("count_comment", countComment);
	}

	public java.lang.Integer getCountComment() {
		return get("count_comment");
	}

	public void setCountView(java.lang.Integer countView) {
		set("count_view", countView);
	}

	public java.lang.Integer getCountView() {
		return get("count_view");
	}

	public void setImageUrl(java.lang.String imageUrl) {
		set("image_url", imageUrl);
	}

	public java.lang.String getImageUrl() {
		return get("image_url");
	}

	public void setPublishTime(java.util.Date publishTime) {
		set("publish_time", publishTime);
	}

	public java.util.Date getPublishTime() {
		return get("publish_time");
	}

	public void setPublishTimeRemark(java.lang.String publishTimeRemark) {
		set("publish_time_remark", publishTimeRemark);
	}

	public java.lang.String getPublishTimeRemark() {
		return get("publish_time_remark");
	}

	public void setPublishUser(java.lang.String publishUser) {
		set("publish_user", publishUser);
	}

	public java.lang.String getPublishUser() {
		return get("publish_user");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

}
