package com.redsea.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.redsea.ext.base.BaseModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSpiderRule<M extends BaseSpiderRule<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setWebsite(java.lang.String website) {
		set("website", website);
	}

	public java.lang.String getWebsite() {
		return get("website");
	}

	public void setTitleRule(java.lang.String titleRule) {
		set("title_rule", titleRule);
	}

	public java.lang.String getTitleRule() {
		return get("title_rule");
	}

	public void setContentRule(java.lang.String contentRule) {
		set("content_rule", contentRule);
	}

	public java.lang.String getContentRule() {
		return get("content_rule");
	}

	public void setSummaryRule(java.lang.String summaryRule) {
		set("summary_rule", summaryRule);
	}

	public java.lang.String getSummaryRule() {
		return get("summary_rule");
	}

	public void setOriginRule(java.lang.String originRule) {
		set("origin_rule", originRule);
	}

	public java.lang.String getOriginRule() {
		return get("origin_rule");
	}

	public void setPublishUserRule(java.lang.String publishUserRule) {
		set("publish_user_rule", publishUserRule);
	}

	public java.lang.String getPublishUserRule() {
		return get("publish_user_rule");
	}

	public void setPublishTimeRule(java.lang.String publishTimeRule) {
		set("publish_time_rule", publishTimeRule);
	}

	public java.lang.String getPublishTimeRule() {
		return get("publish_time_rule");
	}

	

}
