package com.redsea.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.redsea.ext.base.BaseModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTags<M extends BaseTags<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTagName(java.lang.String tagName) {
		set("tag_name", tagName);
	}

	public java.lang.String getTagName() {
		return get("tag_name");
	}

}
