package com.redsea.pojo.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticleRegion<M extends BaseArticleRegion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setArticleId(java.lang.Integer articleId) {
		set("article_id", articleId);
	}

	public java.lang.Integer getArticleId() {
		return get("article_id");
	}

	public void setRegionCode(java.lang.String regionCode) {
		set("region_code", regionCode);
	}

	public java.lang.String getRegionCode() {
		return get("region_code");
	}

}
