package com.redsea.pojo.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysCode<M extends BaseSysCode<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setParamname(java.lang.String paramname) {
		set("paramname", paramname);
	}

	public java.lang.String getParamname() {
		return get("paramname");
	}

	public void setParamtype(java.lang.String paramtype) {
		set("paramtype", paramtype);
	}

	public java.lang.String getParamtype() {
		return get("paramtype");
	}

	public void setParamvalue(java.lang.String paramvalue) {
		set("paramvalue", paramvalue);
	}

	public java.lang.String getParamvalue() {
		return get("paramvalue");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}

	public java.lang.Integer getIsdelete() {
		return get("isdelete");
	}

}
