package com.redsea.model;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;
import com.redsea.common.Consts;
import com.redsea.model.base.BasePeople;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class People extends BasePeople<People> {
	public static final People dao = new People();
	/**
	 * 从缓存中加载用户
	 * @param userId
	 * @return
	 */
	public People loadInSession(String userId) {
		if (StrKit.isBlank(userId)) {
			return null;
		}
		return loadInSession(Long.parseLong(userId));
	}

	/**
	 * 从缓存中加载用户
	 * @param userId
	 * @return
	 */
	public People loadInSession(final long userId) {
		return CacheKit.get(Consts.CacheName.session.get(), userId, new IDataLoader() {
			@Override
			public Object load() {
				return findById(userId);
			}
		});
	}
}
