package com.redsea.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.redsea.model.base.BaseRegionUrl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RegionUrl extends BaseRegionUrl<RegionUrl> {
	public static final RegionUrl dao = new RegionUrl();
	
	public List<RegionUrl> getAllParentData(){
		String sql="SELECT DISTINCT(region_code),code_name from tbl_region_url where parent_code='china'";
		return find(sql);
	}
	public List<Record> getCityData(String regionCode){
		String sql="SELECT DISTINCT(region_code),code_name from tbl_region_url where parent_code='"+regionCode+"'";
		return Db.find(sql);
	}
	public RegionUrl getCityDetailData(Integer type,String regionCode){
		String sql="SELECT * from tbl_region_url where type= ? and region_code= ? ";
		return findFirst(sql,type,regionCode);
	}
}
