package com.redsea.model;

import com.redsea.model.base.BaseSpiderRule;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpiderRule extends BaseSpiderRule<SpiderRule> {
	public static final SpiderRule dao = new SpiderRule();
}
