package com.redsea.model;

import com.redsea.model.base.BaseSpiderJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpiderJob extends BaseSpiderJob<SpiderJob> {
	public static final SpiderJob dao = new SpiderJob();
}
