package com.redsea.model;

import java.util.Map;

import com.jfinal.plugin.ehcache.CacheKit;
import com.redsea.common.CacheConstants;
import com.redsea.model.base.BaseSysCode;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysCode extends BaseSysCode<SysCode> {
	public static final SysCode dao = new SysCode();
	
	public static String getValue(String key){
		Map map=CacheKit.get(CacheConstants.CONSTANTS_CODE_CACHE,CacheConstants.CODE_TABLE_KEY);
		return (String)map.get(key);
	}
}
