package com.redsea.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.redsea.common.Consts;
import com.redsea.model.base.BaseTags;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tags extends BaseTags<Tags> {
	public static final Tags dao = new Tags();
	public List<Tags> getAllByCache(){
		String sql="SELECT  DISTINCT(tag_name),t1.* from tbl_tags t1 LEFT JOIN tbl_article_tags t2 on t1.id=t2.tag_id LEFT JOIN tbl_article t3 on t3.id=t2.article_id ORDER BY t3.count_view DESC limit 12";
		List list=list=Db.findByCache(Consts.CacheName.oneDay.get(), "tagsCache", sql);;
		return list;
		
	}
}
